security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Utilisateur
        property: email

  firewalls:
    dev:
      pattern: ^/(_profiler|_wdt|assets|build)/
      security: false

    admin:
      pattern: ^/admin
      lazy: true
      provider: app_user_provider
      context: shared            # ✅ AJOUT IMPORTANT
      custom_authenticators:
        - App\Security\AdminLoginFormAuthenticator
      logout:
        path: admin_logout
        target: app_public_site

    main:
      lazy: true
      provider: app_user_provider
      context: shared            # ✅ AJOUT IMPORTANT
      entry_point: App\Security\LoginFormAuthenticator
      custom_authenticators:
        - App\Security\LoginFormAuthenticator
      logout:
        path: app_logout
        target: app_public_site

  access_control:
    - { path: ^/admin/login, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_ADMIN }

    - { path: ^/login, roles: PUBLIC_ACCESS }

    # ✅ ton front
    - { path: ^/eventsFront/\d+/(participer|annuler)$, roles: IS_AUTHENTICATED_FULLY }

    - { path: ^/dashboard, roles: ROLE_ADMIN }
    - { path: ^/patient, roles: ROLE_PATIENT }
    - { path: ^/infermier, roles: ROLE_PERSONNEL_MEDICAL }
    - { path: ^/proprietaire, roles: ROLE_PROPRIETAIRE_MEDICAUX }
