security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Utilisateur
        property: email

  firewalls:
    dev:
      pattern: ^/(_profiler|_wdt|assets|build)/
      security: false

    # ✅ Un seul firewall : tout passe par /login (admin + autres)
    main:
      lazy: true
      provider: app_user_provider

      # ✅ ton authenticator unique
      custom_authenticators:
        - App\Security\LoginFormAuthenticator

      logout:
        path: app_logout
        target: app_public_site

  access_control:
    # ✅ Autoriser la page login & reset
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/reset-password, roles: PUBLIC_ACCESS }

    # ✅ Admin PIN (doit être avant /admin)
    - { path: ^/admin/pin, roles: ROLE_ADMIN }

    # ✅ Admin zone
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/dashboard, roles: ROLE_ADMIN }

    # ✅ Rôles front
    - { path: ^/patient, roles: ROLE_PATIENT }
    - { path: ^/infermier, roles: ROLE_PERSONNEL_MEDICAL }
    - { path: ^/proprietaire, roles: ROLE_PROPRIETAIRE_MEDICAUX }

    # ✅ Exemple: actions events protégées
    - { path: ^/eventsFront/\d+/(participer|annuler)$, roles: IS_AUTHENTICATED_FULLY }