vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        rapport_files:
            uri_prefix: /uploads/rapports
            upload_destination: '%kernel.project_dir%/public/uploads/rapports'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
