# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    post_images_dir: '%kernel.project_dir%/public/uploads/posts'
    images_directory: '%kernel.project_dir%/public/uploads/images'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\FrontOffice\EventController:
        public: true
        tags: ['controller.service_arguments']

    App\Controller\FrontOffice\ForumController:
        public: true
        tags: ['controller.service_arguments']

    App\EventListener\CommentNotificationListener:
        tags:
            - { name: kernel.event_listener, event: App\Event\CommentCreatedEvent, method: __invoke }

    App\EventListener\AiMedicalAgentListener:
        tags:
            - { name: kernel.event_listener, event: App\Event\PostCreatedEvent }


