parameters:
    post_images_dir: '%kernel.project_dir%/public/uploads/posts'
    images_directory: '%kernel.project_dir%/public/uploads/images'
    app.url: '%env(APP_URL)%'
    app.mail_from: '%env(MAIL_FROM)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\FrontOffice\EventController:
        public: true
        tags: ['controller.service_arguments']

    App\Controller\FrontOffice\ForumController:
        public: true
        tags: ['controller.service_arguments']

    App\EventListener\CommentNotificationListener:
        tags:
            - { name: kernel.event_listener, event: App\Event\CommentCreatedEvent, method: __invoke }

    App\EventListener\AiMedicalAgentListener:
        tags:
            - { name: kernel.event_listener, event: App\Event\PostCreatedEvent }

    App\Service\EventReminderService:
        arguments:
            $fromEmail: '%app.mail_from%'

    App\Service\StripeCheckoutService:
        arguments:
            $stripeSecretKey: '%env(string:STRIPE_SECRET_KEY)%'
            $stripeCurrency: '%env(string:STRIPE_CURRENCY)%'
            $stripeApiBaseUrl: '%env(string:STRIPE_API_BASE_URL)%'
