parameters:
    post_images_dir: '%kernel.project_dir%/public/uploads/posts'
    images_directory: '%kernel.project_dir%/public/uploads/images'
    app.url: '%env(APP_URL)%'
    app.mail_from: '%env(MAIL_FROM)%'
    app.image_processor.api_url: '%env(string:IMAGE_PROCESSOR_API_URL)%'
    app.image_processor.api_key: '%env(string:IMAGE_PROCESSOR_API_KEY)%'
    app.image_processor.auth_header: '%env(string:IMAGE_PROCESSOR_AUTH_HEADER)%'
    app.image_processor.auth_prefix: '%env(string:IMAGE_PROCESSOR_AUTH_PREFIX)%'
    app.twilio.account_sid: '%env(default::TWILIO_ACCOUNT_SID)%'
    app.twilio.auth_token: '%env(default::TWILIO_AUTH_TOKEN)%'
    app.twilio.from_number: '%env(default::TWILIO_FROM_NUMBER)%'
    app.twilio.stock_alert_to_number: '%env(default::TWILIO_STOCK_ALERT_TO_NUMBER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\FrontOffice\EventController:
        public: true
        tags: ['controller.service_arguments']

    App\Controller\FrontOffice\ForumController:
        public: true
        tags: ['controller.service_arguments']

    App\EventListener\CommentNotificationListener:
        tags:
            - { name: kernel.event_listener, event: App\Event\CommentCreatedEvent, method: __invoke }

    App\EventListener\AiMedicalAgentListener:
        tags:
            - { name: kernel.event_listener, event: App\Event\PostCreatedEvent }

    App\Service\EventReminderService:
        arguments:
            $fromEmail: '%app.mail_from%'

    App\Service\ImageProcessor:
        arguments:
            $apiUrl: '%app.image_processor.api_url%'
            $apiKey: '%app.image_processor.api_key%'
            $targetDirectory: '%images_directory%'
            $authHeaderName: '%app.image_processor.auth_header%'
            $authHeaderPrefix: '%app.image_processor.auth_prefix%'

    App\Service\StripeCheckoutService:
        arguments:
            $stripeSecretKey: '%env(string:STRIPE_SECRET_KEY)%'
            $stripeCurrency: '%env(string:STRIPE_CURRENCY)%'
            $stripeApiBaseUrl: '%env(string:STRIPE_API_BASE_URL)%'

    App\Service\TwilioSmsService:
        arguments:
            $accountSid: '%app.twilio.account_sid%'
            $authToken: '%app.twilio.auth_token%'
            $fromNumber: '%app.twilio.from_number%'
            $toNumber: '%app.twilio.stock_alert_to_number%'
    App\Service\WeatherService:
        arguments:
            $apiKey: '%env(WEATHER_API_KEY)%'
